version: "3.8"

services:
  node_app:
    build:
      context: .
      target: production
      environment:
        - NODE_ENV=production
        - MONGODB_URI=mongodb://mongo:27017/ai_assistant
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: npm start
