version: "3.8"

services:
  node_app:
    build:
      context: .
      target: prod
    container_name: ai-code-assistant
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  mongo:
    image: mongo:6.0
    container_name: ai-assistant-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=ai_assistant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

volumes:
  mongo-data:
    name: ai-assistant-mongodb-data

networks:
  app-network:
    name: ai-assistant-network
    driver: bridge
