version: "3.8"

services:
  node_app:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/ai_assistant
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: ["npm", "run", "dev"]
