
export const schema = {
  title: "LLM Code Review", // Title is often optional for the API
  description: "Schema for representing a line-by-line code review generated by an LLM.", // Description is often optional for the API
  type: "object", // Using standard lowercase JSON schema types
  properties: {
    overview: {
      description: "A general summary of the code review findings.",
      type: "string",
    },
    line_reviews: {
      description: "An array of specific reviews for individual lines of code.",
      type: "array",
      items: {
        type: "object",
        properties: {
          line: {
            description:
              "The line number in the original code that the review pertains to.",
            type: "integer", // Use "integer" or "number" based on precision needed
            minimum: 1, // Constraints like minimum are supported
          },
          review: {
            description: "The specific comment or suggestion for the line.",
            type: "string",
          },
          review_type: {
            description: "The category or type of the review comment.",
            type: "string",
            enum: [
              // Enums are supported
              "suggestion",
              "issue",
              "question",
              "nitpick",
              "clarification"
            ],
          },
          reviewed_line: {
            description: "The line of code that was reviewed.",
            type: "string",
          }
        },
        required: [
          // Required fields within the item object
          "line",
          "review",
          "review_type",
          "reviewed_line",
        ],
      },
    },
    udiff: {
      description:
        "A unified diff representing the suggested code changes, if applicable.",
      type: "string",
    },
  },
  required: [
    // Required fields at the top level
    "overview",
    "line_reviews",
  ],
};


